# Generated by Django 3.2.6 on 2021-09-13 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Staff'), (3, 'Customer')]),
        ),
    ]
